version: '3.8'

services:
  # Angular Frontend Development Server
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For file watching in Docker
    restart: unless-stopped
    networks:
      - dev-network
    stdin_open: true
    tty: true

  # Backend Development Server (if you have one)
  # backend-dev:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://eventboard:dev_password@database-dev:5432/eventboard_dev
  #   restart: unless-stopped
  #   networks:
  #     - dev-network
  #   depends_on:
  #     - database-dev

  # Development Database
  # database-dev:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: eventboard_dev
  #     POSTGRES_USER: eventboard
  #     POSTGRES_PASSWORD: dev_password
  #   volumes:
  #     - postgres_dev_data:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"  # Different port to avoid conflicts
  #   restart: unless-stopped
  #   networks:
  #     - dev-network

networks:
  dev-network:
    driver: bridge

# volumes:
#   postgres_dev_data: